# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alogoEmailRecipients',
        ),
    ]
